name: SonarCloud .NET Begin

description: Install SonarScanner for .NET and start analysis (begin)

inputs:
  token:
    description: SonarCloud token
    required: true
  org:
    description: SonarCloud organization key
    required: true
  projectKey:
    description: SonarCloud project key
    required: true
  branch:
    description: Branch name to attribute analysis to
    required: false
    default: ""
  cobertura_glob:
    description: Cobertura report glob for C# coverage
    required: false
    default: "**/TestResults/**/coverage.opencover.xml"
  pr_key:
    description: Pull request number (for PR analysis)
    required: false
    default: ""
  pr_branch:
    description: Pull request branch name (head)
    required: false
    default: ""
  pr_base:
    description: Pull request base branch name
    required: false
    default: ""
  js_lcov:
    description: Path to JS/TS lcov report (for web coverage)
    required: true
  sonar_exclusions:
    description: SonarCloud file exclusions (comma-separated patterns)
    required: true
  sonar_coverage_exclusions:
    description: SonarCloud coverage exclusions (comma-separated patterns)
    required: true
  sonar_infra_exclusions:
    description: Infrastructure-specific exclusions (optional)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Install SonarScanner for .NET
      shell: bash
      run: dotnet tool install --global dotnet-sonarscanner || true

    - name: SonarCloud Begin
      shell: bash
      env:
        SONAR_TOKEN: ${{ inputs.token }}
        SONAR_ORG: ${{ inputs.org }}
        SONAR_PROJECT_KEY: ${{ inputs.projectKey }}
        BRANCH: ${{ inputs.branch }}
        COB_GLOB: ${{ inputs.cobertura_glob }}
        PR_KEY: ${{ inputs.pr_key }}
        PR_BRANCH: ${{ inputs.pr_branch }}
        PR_BASE: ${{ inputs.pr_base }}
        JS_LCOV: ${{ inputs.js_lcov }}
        SONAR_EXCLUSIONS: ${{ inputs.sonar_exclusions }}
        SONAR_COVERAGE_EXCLUSIONS: ${{ inputs.sonar_coverage_exclusions }}
        SONAR_INFRA_EXCLUSIONS: ${{ inputs.sonar_infra_exclusions }}
      run: |
        set -e
        export PATH="$PATH:$HOME/.dotnet/tools"
        # Force project base dir to the repository root for consistent behavior across Scanner v8+ changes
        PBDIR="${GITHUB_WORKSPACE:-$(pwd)}"
        
        # Build exclusions dynamically
        FULL_EXCLUSIONS="${SONAR_EXCLUSIONS}"
        if [ -n "$SONAR_INFRA_EXCLUSIONS" ]; then
          FULL_EXCLUSIONS="${FULL_EXCLUSIONS},${SONAR_INFRA_EXCLUSIONS}"
        fi
        
        ARGS=(
          "/o:${SONAR_ORG}"
          "/k:${SONAR_PROJECT_KEY}"
          "/d:sonar.host.url=https://sonarcloud.io"
          "/d:sonar.token=${SONAR_TOKEN}"
          "/d:sonar.cs.opencover.reportsPaths=${COB_GLOB}"
          "/d:sonar.projectBaseDir=${PBDIR}"
          "/d:sonar.scanner.scanAll=true"
          "/d:sonar.sources=."
          "/d:sonar.exclusions=${FULL_EXCLUSIONS}"
          "/d:sonar.coverage.exclusions=${SONAR_COVERAGE_EXCLUSIONS}"
          "/d:sonar.cpd.exclusions=**/Migrations/**/*.cs,**/*.Designer.cs,**/*.generated.cs,**/*ModelSnapshot.cs"
          "/d:sonar.test.inclusions=**/*.Tests/**,**/*Tests.cs,**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx"
          "/d:sonar.cs.vstest.reportsPaths=**/TestResults/**/*.trx"
        )
        # JS/TS coverage (lcov) for web
        if [ -n "$JS_LCOV" ]; then
          ARGS+=("/d:sonar.javascript.lcov.reportPaths=${JS_LCOV}")
        fi
        # If PR metadata is provided, configure PR analysis and DO NOT set branch name
        if [ -n "$PR_KEY" ] && [ -n "$PR_BRANCH" ] && [ -n "$PR_BASE" ]; then
          ARGS+=(
            "/d:sonar.pullrequest.key=${PR_KEY}"
            "/d:sonar.pullrequest.branch=${PR_BRANCH}"
            "/d:sonar.pullrequest.base=${PR_BASE}"
          )
        elif [ -n "$BRANCH" ]; then
          ARGS+=("/d:sonar.branch.name=${BRANCH}")
        fi
        dotnet sonarscanner begin "${ARGS[@]}"